INSERT INTO techpack_versions VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS','R1A01','BASE','E','ERBS','CXP111111','LTE','','CXP111111');
INSERT INTO reportable_entity VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01','BASE_E_ERBS_COMMON','BASE','','','Base keys view properties');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:date_id','date_id',0,'key','STRING','TEXT','1','DATE_ID');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:date_id','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:granularity','granularity',1,'key','BIGINT','TEXT','0','GRANULARITY');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:granularity','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:moid','moid',2,'key','STRING','TEXT','0','MOID');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:moid','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:nedn','nedn',3,'key','STRING','TEXT','0','NEDN');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:nedn','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:node','node',4,'key','STRING','TEXT','0','NODE NAME');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:node','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:ropendtime','ropendtime',5,'key','TIMESTAMP','TEXT','0','ROP ENDTIME');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:ropendtime','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:utc_timestamp','utc_timestamp',6,'key','TIMESTAMP','TEXT','0','UTC TIMESTAMP');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:utc_timestamp','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:local_timestamp','local_timestamp',7,'key','TIMESTAMP','TEXT','0','LOCAL TIMESTAMP');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON:local_timestamp','BASE_E_ERBS_R1A01','BASE_E_ERBS_R1A01:BASE_E_ERBS_COMMON','','');
INSERT INTO flow_scheduling VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','FileCollection','com.ericsson.kyo.workers.FileCollectionWorker','True','15','0','0');
INSERT INTO flow_configuration VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','FileCollection','com.ericsson.kyo.workers.FileCollectionWorker','inputDirectory=/mnt/nfsshare/data/pmMediation/segment1/XML/WRAN/LTE/ ','','');
INSERT INTO flow_configuration VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','FileParsing','com.ericsson.kyo.workers.SparkLauncherWorker','SparkLauncherMainClass=com.ericsson.kyo.workers.SparkStarter::rowTag=md::OutputPath=maprfs:///PM/E/ERBS/$VERSION','PM_E_ERBS','FileCollection');
INSERT INTO designrules VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','RuleForAllMOs','BASE_E_ERBS',0 ,'ALL','','','');
INSERT INTO designrules VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','Vector','RuleForAllMOs',0 ,'equals','counterType','PDF','_V');
INSERT INTO designrules VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','Flex','RuleForAllMOs',1 ,'startswith','name','pmFlex','_FLEX');
INSERT INTO designrules VALUES ('BASE_E_ERBS_R1A01','PM_E_ERBS','Gauge/Peg','RuleForAllMOs',2 ,'startswith','name','pm','');
INSERT INTO retention_plan VALUES ('SHORTTERM','7','3');
INSERT INTO retention_plan VALUES ('MEDIUMTERM','14','3');
INSERT INTO retention_plan VALUES ('LONGTERM','21','3');
