INSERT INTO techpack_versions VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME','R1A01','BASE','E','SGSNMME','CXP111112','LTE','','CXP111112');
INSERT INTO reportable_entity VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_COMMON','BASE','','','Base keys view properties');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:date_id','date_id',0,'key','STRING','TEXT','1','DATE_ID');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:date_id','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:granularity','granularity',1,'key','BIGINT','TEXT','0','GRANULARITY');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:granularity','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:moid','moid',2,'key','STRING','TEXT','0','MOID');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:moid','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:node','node',4,'key','STRING','TEXT','0','NODE NAME');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:node','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:ropendtime','ropendtime',5,'key','TIMESTAMP','TEXT','0','ROP ENDTIME');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:ropendtime','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:utc_timestamp','utc_timestamp',6,'key','TIMESTAMP','TEXT','0','UTC TIMESTAMP');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:utc_timestamp','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO reportable_entity_columns VALUES ('BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:local_timestamp','local_timestamp',7,'key','TIMESTAMP','TEXT','0','LOCAL TIMESTAMP');
INSERT INTO reportable_entity_column_source VALUES ('BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON:local_timestamp','BASE_E_SGSNMME_R1A01','BASE_E_SGSNMME_R1A01:BASE_E_SGSNMME_COMMON','','');
INSERT INTO flow_scheduling VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME','FileCollection','com.ericsson.kyo.workers.FileCollectionWorker','True','15','0','0');
INSERT INTO flow_configuration VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME','FileCollection','com.ericsson.kyo.workers.FileCollectionWorker','inputDirectory=/mnt/nfsshare/data/sgw/sgwcg/xml/gsn/sgsnmmecom/ ','','');
INSERT INTO flow_configuration VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME','FileParsing','com.ericsson.kyo.workers.SparkLauncherWorker','SparkLauncherMainClass=com.ericsson.kyo.workers.SGSNSparkStarter::rowTag=measData::OutputPath=maprfs:///PM/E/SGSNMME/$VERSION','PM_E_SGSNMME','FileCollection');
INSERT INTO flow_scheduling VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME_AGEING','DataAgeing','com.ericsson.kyo.workers.SparkLauncherWorker','True','1440','0','0');
INSERT INTO flow_configuration VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME_AGEING','DataAgeing','com.ericsson.kyo.workers.SparkLauncherWorker','SparkLauncherMainClass=com.ericsson.kyo.workers.AgeingSparkStarter::OutputPath=maprfs:///PM/E/SGSNMME/$VERSION','','');
INSERT INTO flow_scheduling VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME_ADD_PARTITION','AddPartitions','com.ericsson.kyo.workers.AddPartitions','True','1440','0','0');
INSERT INTO flow_configuration VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME_ADD_PARTITION','AddPartitions','com.ericsson.kyo.workers.AddPartitions','','','');
INSERT INTO flow_scheduling VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME_DELETE_PARTITION','DeletePartitions','com.ericsson.kyo.workers.DropPartitions','True','1440','0','0');
INSERT INTO flow_configuration VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME_DELETE_PARTITION','DeletePartitions','com.ericsson.kyo.workers.DropPartitions','','','');
INSERT INTO designrules VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME','RuleForAllMOs','BASE_E_SGSNMME',0 ,'ALL','','','');
INSERT INTO designrules VALUES ('BASE_E_SGSNMME_R1A01','PM_E_SGSNMME','Gauge/Peg','RuleForAllMOs',0 ,'ALL','','','');
