DROP TABLE if exists TECHPACK_VERSIONS;
DROP TABLE if exists SUPPORTED_NODE_VERSIONS;
DROP TABLE if exists NODE_MANAGED_OBJECTS;
DROP TABLE if exists NODE_MANAGED_OBJECTS_HIERARCHY;
DROP TABLE if exists REPORTABLE_ENTITY;
DROP TABLE if exists REPORTABLE_ENTITY_COLUMNS;

CREATE TABLE TECHPACK_VERSIONS
(
	TECHPACK_VERSION_ID varchar(128),
	TECHPACK_NAME varchar(128),
	TECHPACK_RELEASE varchar(128),
	TECHPACK_VERSION varchar(128),
	PRODUCT_NUMBER varchar(128),
	FEATURE_NAME varchar(128),
	DESCRIPTION varchar(255),
	LICENSE varchar(128),
	DEPENDENCY varchar(128)  
);

CREATE TABLE SUPPORTED_NODE_VERSIONS
(
	TECHPACK_VERSION_ID varchar(128),
	NODE_MODEL_VERSION_ID varchar(128),
	MODEL_NAME varchar(128),
	MODEL_VERSION varchar(128),
	NODE_VERSION  varchar(128),
	DESCRIPTION varchar(255)
);

CREATE TABLE NODE_MANAGED_OBJECTS
(
	TECHPACK_VERSION_ID varchar(128),
	NODE_MODEL_VERSION_ID varchar(128),
	MO_NAME varchar(128),
	MO_DESCRIPTION varchar(255)
);

CREATE TABLE NODE_MANAGED_OBJECTS_HIERARCHY
(
	TECHPACK_VERSION_ID varchar(128),
	NODE_MODEL_VERSION_ID varchar(128),
	PARENT_MO_NAME varchar(128),
	CHILD_MO_NAME varchar(128)
);

CREATE TABLE REPORTABLE_ENTITY
(
	TECHPACK_VERSION_ID varchar(128),
	REPORTABLE_ENTITY_NAME varchar(128),
	REPORTABLE_ENTITY_DESCRIPTION varchar(255),
	DERIVED_FROM varchar(128)
);

CREATE TABLE REPORTABLE_ENTITY_COLUMNS
(
	TECHPACK_VERSION_ID varchar(128),
	REPORTABLE_ENTITY_ID varchar(128),
	PERSISTENCE_ENTITY_ID varchar(128),
	COLUMN_NAME varchar(128),
	COLUMN_TYPE varchar(128),
	COLUMN_DESCRIPTION varchar(255),
	PERSISTENCE_ENTITY_COLUMN_NAME varchar(128)
);


DROP TABLE if exists PERSISTENCE_ENTITY;
DROP TABLE if exists PERSISTENCE_ENTITY_COLUMNS;
DROP TABLE if exists FLOW_CONFIGURATION;
DROP TABLE if exists FLOW_SCHEDULING;
DROP TABLE if exists FILEBACKLOG;

CREATE TABLE PERSISTENCE_ENTITY
(
	TECHPACK_VERSION_ID varchar(128),
	PERSISTENCE_ENTITY_ID varchar(128),
	PERSISTENCE_ENTITY_NAME varchar(128),
	NODE_MODEL_VERSION_ID varchar(128),
	DERIVED_FROM varchar(128),
	DERIVE_TYPE varchar(128)
);

CREATE TABLE PERSISTENCE_ENTITY_COLUMNS
(
	TECHPACK_VERSION_ID varchar(128),
	NODE_MODEL_VERSION_ID varchar(128),
	PERSISTENCE_ENTITY_ID varchar(128),
	COLUMN_ORDER varchar(128),
	COLUMN_NAME varchar(128),
	COLUMN_TYPE varchar(128),
	COLUMN_DESCRIPTION varchar(255),
	PARTITION_BY SMALLINT,
	MO_NAME  varchar(128),
	MO_ATTRIBUTE_NAME varchar(128)
);

CREATE TABLE FLOW_CONFIGURATION
(
	TECHPACK_VERSION_ID varchar(128),
	FLOW_NAME varchar(128),
	WORKER_NAME varchar(128),
	WORKER_CONFIG varchar(128),
	DEPENDENCY_FLOW_NAME varchar(128),
	DEPENDENCY_WORKER_NAME varchar(128)
);

CREATE TABLE FLOW_SCHEDULING
(
	TECHPACK_VERSION_ID varchar(128),
	FLOW_NAME varchar(128),
	WORKER_NAME varchar(128),
	REOCCURING varchar(128),
	ROP_INTERVAL int,
	ROP_OFFSET int
);

CREATE TABLE FILEBACKLOG
(
	TECHPACK_VERSION_ID varchar(128),
	FLOW_NAME varchar(128),
	WORKER_NAME varchar(128),
	FILELIST TEXT []
);


