hdfs:
  hdfs-namenode-k8s:
    persistence:
      size: 10Gi
    jmxExporter:
      enabled: true
      images:
        repository: armdocker.rnd.ericsson.se/aia_snapshots
        name: prometheus-jmx-exporter-0.3.1
        tag: 0.0.1-SNAPSHOT-17
      servicePort: 21002
      destPort: 11002
    podAnnotations:
      "prometheus.io/scrape": "true"
  hdfs-journalnode-k8s:
    persistence:
      size: 10Gi
  hdfs-datanode-k8s:
    jmxExporter:
      enabled: true
      images:
        repository: armdocker.rnd.ericsson.se/aia_snapshots
        name: prometheus-jmx-exporter-0.3.1
        tag: 0.0.1-SNAPSHOT-17
      servicePort: 21003
      destPort: 11003
    podAnnotations:
      "prometheus.io/scrape": "true"

drill:
  fullnameOverride: kyo-drill
  zkUrl: eric-data-coordinator-zk:2181
  service:
    type: NodePort
  ingress:
    enabled: true
    hosts:
      - drill.kyo.ericsson.se
  config:
    configMaps:
      - kyo-drill-config
      - kyo-hdfs-config

eric-data-engine-sk:
  worker:
    replicas: 6
  jmx:
    enabled: true
  environmentOverrides:
    SPARK_WORKER_CORES: 4
    SPARK_WORKER_MEMORY: 4g
  volumes: |
    - name: kyo-nfs
      nfs:
        path: /export/pvc-891865bb-2bc0-11e9-8f95-fa163e9b416a/
        server: 192.168.239.40
    - name: kyo-hdfs-config
      configMap:
        name: kyo-hdfs-config

  volumeMounts: |
    - mountPath: /data/
      name: kyo-nfs
    - mountPath: /etc/hadoop/conf/
      name: kyo-hdfs-config

eric-pm-server:
  nameOverride: kyo-pm-server
  rbac:
    appMonitoring:
      enabled: true
      configFileCreate: false
    clusterMonitoring:
      enabled: true
  server:
    persistentVolume:
      enabled: true

eric-data-coordinator-zk:
  persistantVolumeClaim:
    storageClassName: erikube-cinder

## Tags and conditions for triggering a group of relevant subcharts.
tags:
  ## Trigger all subcharts required for high availability. Enabled by default.
  ha: true

  ## Trigger all subcharts required for using Kerberos. Disabled by default.
  kerberos: false

  ## Trigger all subcharts required for non-HA setup. Disabled by default.
  simple: false

## ------------------------------------------------------------------------------
## Global values affecting all sub-charts:
## ------------------------------------------------------------------------------
global:
  dataNodeHostPath:
    - /hostpath/
  zookeeperQuorumOverride: eric-data-coordinator-zk:2181

  ## Parameters for determining which Unix user and group IDs to use in pods.
  ## Persistent volume permission may need to match these.
  podSecurityContext:
    enabled: false
    runAsUser: 0
    fsGroup: 1000

  ## Whether or not to expect namenodes in the HA setup.
  namenodeHAEnabled: true

  ## The number of zookeeper server to have in the quorum.
  ## This should match zookeeper.replicaCount above. Used only when
  ## namenodeHAEnabled is set.
  zookeeperQuorumSize: 3

  ## Override zookeeper quorum address. Zookeeper is used for determining which namenode
  ## instance is active. Separated by the comma character. Used only when
  ## namenodeHAEnabled is set.
  ##
  # zookeeperQuorumOverride: zk-0.zk-svc.default.svc.cluster.local:2181,zk-1.zk-svc.default.svc.cluster.local:2181,zk-2.zk-svc.default.svc.cluster.local:2181

  ## How many journal nodes to launch as a quorum. Used only when
  ## namenodeHAEnabled is set.
  journalnodeQuorumSize: 3

  ## Whether or not to enable default affinity setting.
  defaultAffinityEnabled: true

  ## Whether or not Kerberos support is enabled.
  kerberosEnabled: false

  ## Effective only if Kerberos is enabled. Override th name of the k8s
  ## ConfigMap containing the kerberos config file.
  ##
  # kerberosConfigMapOverride: kerberos-config

  ## Effective only if Kerberos is enabled. Name of the kerberos config file inside
  ## the config map.
  kerberosConfigFileName: krb5.conf

  ## Effective only if Kerberos is enabled. Override the name of the k8s Secret
  ## containing the kerberos keytab files of per-host HDFS principals.
  ## The secret should have multiple data items. Each data item name
  ## should be formatted as:
  ##    `HOST-NAME.keytab`
  ## where HOST-NAME should match the cluster node
  ## host name that each per-host hdfs principal is associated with.
  ##
  # kerberosKeytabsSecretOverride: hdfs-kerberos-keytabs

  ## Required to be non-empty if Kerberos is enabled. Specify your Kerberos realm name.
  ## This should match the realm name in your Kerberos config file.
  kerberosRealm: MYCOMPANY.COM

  ## Effective only if Kerberos is enabled. Enable protection of datanodes using
  ## the jsvc utility. See the reference doc at
  ## https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html#Secure_DataNode
  jsvcEnabled: true
